# Generated by Django 5.0.3 on 2024-03-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_announcements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcements',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='announcements',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
