# Generated by Django 5.0.3 on 2024-03-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_remove_marks_subject1_remove_marks_subject2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincredentials',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='marks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentcredentials',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
